name = "Catppuccin"
brightness = "dark"

[colors]
background = "#1E1E2E"
surface = "#181825"
surface_variant = "#11111B"
primary = "#89B4FA"
on_primary = "#111111"
secondary = "#CBA6F7"
on_secondary = "#111111"
accent = "#F5C2E7"
error = "#F38BA8"
on_error = "#111111"
warning = "#F9E2AF"
on_warning = "#111111"
success = "#A6E3A1"
on_success = "#111111"
info = "#94E2D5"
text = "#CDD6F4"
text_muted = "#BAC2DE"
border = "#313244"
border_active = "#45475A"
border_subtle = "#585B70"
selection = "#89B4FA"
selected_text = "#1E1E2E"

[markdown]
text = "#CDD6F4"
heading = "#CBA6F7"
link = "#89B4FA"
code = "#A6E3A1"
block_quote = "#F9E2AF"
emphasis = "#F9E2AF"
strong = "#FAB387"
rule = "#A6ADC8"
list = "#89B4FA"
code_block = "#CDD6F4"

[syntax]
default = "#CDD6F4"
comment = "#9399B2"
keyword = "#CBA6F7"
storage = "#CBA6F7"
function = "#89B4FA"
type = "#F9E2AF"
string = "#A6E3A1"
constant = "#FAB387"
number = "#FAB387"
variable = "#F38BA8"
tag = "#F9E2AF"
attribute = "#F38BA8"
operator = "#89DCEB"
punctuation = "#CDD6F4"
meta = "#CDD6F4"
